#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap us &

# Set the wallpaper
feh --bg-fill ~/Pictures/background.jpg

# Start the compositor
picom --config ~/.config/picom.conf

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_width         0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
